"use client"

import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Accordion, AccordionItem } from "@heroui/accordion";
import { staticFundingParticipants, calculateStaticTotalUsdcRaised } from '@/data/staticFundingParticipants';

export default function FundingParticipantsPage() {
  // Use static data directly
  const participantsData = staticFundingParticipants;
  
  // Sort participants by contribution amount (descending) and slice to top 100
  const sortedTopParticipants = participantsData
    .sort((a, b) => b.labsQuantity - a.labsQuantity)
    .slice(0, 100);


  const formatWalletAddress = (address: string) => {
    return `${address.slice(0, 6)}...${address.slice(-4)}`;
  };

  const formatNumber = (num: number) => {
    return new Intl.NumberFormat('en-US', {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(num);
  };

  const formatPercentage = (num: number) => {
    return new Intl.NumberFormat('en-US', {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
      style: 'percent'
    }).format(num / 100);
  };

  const formatCurrency = (num: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(num);
  };

  // Calculate total USDC raised from static data
  const totalUsdcRaised = calculateStaticTotalUsdcRaised();

  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      {/* Hero Section */}
      <main className="flex-1 pt-32 pb-16">
        <div className="container mx-auto px-4">
          <div className="max-w-6xl mx-auto">
            {/* Header */}
            <div className="text-center mb-8 md:mb-16">
              <h1 className="text-3xl sm:text-4xl md:text-6xl font-bold tracking-tight mb-8">
                <span className="font-extralight drop-shadow-[0_0_0.3rem_#ffffff70] text-white">Fundraising Campaign</span>
                <br className="sm:hidden" />

              </h1>
              
              {/* Revenue Share & Stats Combined */}
              <div className="bg-black/30 backdrop-blur-md border border-white/10 rounded-xl p-4 md:p-8 max-w-6xl mx-auto mb-12 hover:border-white/20 transition-all duration-500 shadow-lg">
                <div className="space-y-8">
                  <div className="flex flex-col lg:flex-row lg:items-center gap-8">
                    {/* Revenue Share Info - Left Side */}
                    <div className="flex-1 text-center lg:text-left">
                      <h3 className="text-xl md:text-2xl font-bold text-white mb-3">OPX Revenue Share Incentive:</h3>
                      <p className="text-sm md:text-base text-white/80 mb-4">
                        <span className="text-[#4a85ff] font-bold text-base md:text-base">10%</span> of all fees generated by <strong>OPX</strong> in the first 2 months will be distributed to participants based on their share of the total amount raised for the fundraiser post-launch
                      </p>
                      <p className="text-xs text-white/60">
                        * Must hold equal to or greater than the amount purchased from the DAO until Sept 30, 2025 <br />
                        * OPX launch date is Q4 2025 <br />
                      </p>
                    </div>
                    
                    {/* Stats Grid - Right Side */}
                    <div className="flex-shrink-0">
                      <div className="grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-1 xl:grid-cols-3 gap-4 lg:gap-3">
                        <div className="bg-gradient-to-br from-white/5 to-white/[0.02] rounded-xl p-4 border border-white/10 text-center min-w-[140px]">
                          <div className="text-lg md:text-xl font-bold text-[#4a85ff]">
                            15
                          </div>
                          <div className="text-xs text-white/70">Qualified Participants</div>
                        </div>
                        <div className="bg-gradient-to-br from-white/5 to-white/[0.02] rounded-xl p-4 border border-white/10 text-center min-w-[140px]">
                          <div className="text-lg md:text-xl font-bold text-[#4a85ff]">
                            4,427,094
                          </div>
                          <div className="text-xs text-white/70">Total $LABS Purchased</div>
                        </div>
                        <div className="bg-gradient-to-br from-white/5 to-white/[0.02] rounded-xl p-4 border border-white/10 text-center min-w-[140px]">
                          <div className="text-lg md:text-xl font-bold text-[#4a85ff] drop-shadow-[0_0_16px_#4a85ffcc]">
                            $20,000
                          </div>
                          <div className="text-xs text-white/70">USDC Raised</div>
                        </div>
                      </div>
                      

                    </div>
                  </div>
                  
                  {/* Public Funding Goals Section */}
                  <div className="mt-4 pt-4 border-t border-white/10">
                    <div className="space-y-3">
                      {/* Goal Item */}
                      <div className="bg-gradient-to-br from-white/5 to-white/[0.02] rounded-xl p-2 md:p-4 border border-white/10 hover:border-white/20 transition-all duration-300">
                        <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-3">
                          {/* Goal Title with Checkmark */}
                          <div className="flex items-center gap-2 flex-1">
                            {/* Green Checkmark */}
                            <div className="flex-shrink-0">
                              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="drop-shadow-[0_0_6px_#22c55e] sm:w-5 sm:h-5">
                                <circle cx="12" cy="12" r="12" fill="#22c55e" fillOpacity="0.15" />
                                <path d="M7 13.5L10.5 17L17 10.5" stroke="#22c55e" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"/>
                              </svg>
                            </div>
                            
                            {/* Goal Title - Left aligned */}
                            <a 
                              href="https://v2.realms.today/dao/5PP7vKjJyLw1MR55LoexRsCj3CpZj9MdD6aNXRrvxG42/proposal/HRCn9Ti4GzEiA2i7rRV74osCxwxPK9i5pDVzfy8phSgT"
                              target="_blank"
                              rel="noopener noreferrer"
                              className="text-white/75 font-medium text-sm sm:text-base md:text-lg text-left underline decoration-dotted decoration-white/30 hover:decoration-[#4a85ff] transition-colors duration-300"
                            >
                              Hello Moon Collaboration/Partnership - Finalize OPX Build
                            </a>
                          </div>
                          
                          {/* Progress Bar */}
                          <div className="flex-shrink-0 min-w-[180px] sm:min-w-[200px] lg:min-w-[250px]">
                            <div className="space-y-1.5">
                              <div className="flex justify-between items-center text-xs sm:text-sm">
                                <span className="text-white/70">Goal: {formatCurrency(20000)}</span>
                                <span className="text-green-400 font-semibold drop-shadow-[0_0_8px_rgba(34,197,94,0.8)]">{Math.min(100, Math.round((totalUsdcRaised / 20000) * 100))}%</span>
                              </div>
                              <div className="w-full bg-white/10 rounded-full h-1 sm:h-1.5 overflow-hidden shadow-[inset_0_1px_2px_rgba(0,0,0,0.3)]">
                                <div 
                                  className="h-full bg-green-400 rounded-full transition-all duration-1000 ease-out shadow-[0_0_12px_rgba(34,197,94,0.8),0_0_24px_rgba(34,197,94,0.4)]"
                                  style={{ width: `${Math.min(100, (totalUsdcRaised / 20000) * 100)}%` }}
                                />
                              </div>
                              <div className="text-xs text-white/60 text-right">
                                {formatCurrency(totalUsdcRaised)} raised
                              </div>
                            </div>
                          </div>
                        </div>
                        
                        {/* Participants Accordion */}
                        <div className="mt-4 pt-4 border-t border-white/10">
                          <Accordion 
                            isCompact
                            variant="splitted"
                            className="px-0"
                            itemClasses={{
                              base: "px-0 bg-transparent border-none shadow-none",
                              title: "text-lg md:text-xl font-medium text-white/90",
                              trigger: "px-0 py-2 hover:bg-white/5 transition-colors rounded-lg",
                              content: "px-0 pb-0 pt-2",
                              indicator: "text-white/70 transition-transform duration-200"
                            }}
                          >
                            <AccordionItem 
                              key="participants" 
                              aria-label="Qualified Participants" 
                              title="Qualified Participants"
                              subtitle={
                                <a 
                                  href="https://docs.google.com/spreadsheets/d/1VH7rL9M4Oa8g5n2y8sgwoPSc-9u_zK_LQ7qYT8i1vbY/edit?usp=sharing"
                                  target="_blank"
                                  rel="noopener noreferrer"
                                  onClick={(e) => e.stopPropagation()}
                                  className="text-white/60 text-sm underline decoration-dotted decoration-white/30 hover:decoration-[#4a85ff] transition-colors duration-300"
                                >
                                  View Snapshot taken: 10/02/2025 7:30PM EST
                                </a>
                              }
                            >
                              {/* Desktop Table */}
                              <div className="hidden md:block overflow-x-auto">
                                <table className="w-full table-fixed">
                                  <colgroup>
                                    <col className="w-[30%]" />
                                    <col className="w-[25%]" />
                                    <col className="w-[22.5%]" />
                                    <col className="w-[22.5%]" />
                                  </colgroup>
                                  <thead>
                                    <tr className="border-b border-white/10">
                                      <th className="text-left py-4 px-4 text-white/80 font-medium">
                                        <div className="flex items-center gap-2">
                                          Wallet Address
                                          <div className="relative group">
                                            <svg className="w-4 h-4 text-white/40 hover:text-white/70 transition-colors cursor-help" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                            </svg>
                                            <div className="absolute left-1/2 -translate-x-1/2 top-6 z-20 opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity duration-200 whitespace-nowrap">
                                              <div className="bg-black/80 backdrop-blur-md border border-white/20 rounded-lg p-2 shadow-lg">
                                                <p className="text-xs text-white/90">Solana wallet address of the participant</p>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </th>
                                      <th className="text-right py-4 px-4 text-white/80 font-medium">
                                        <div className="flex items-center justify-end gap-2">
                                          $LABS Quantity
                                          <div className="relative group">
                                            <svg className="w-4 h-4 text-white/40 hover:text-white/70 transition-colors cursor-help" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                            </svg>
                                            <div className="absolute right-0 top-6 z-20 opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity duration-200 whitespace-nowrap">
                                              <div className="bg-black/80 backdrop-blur-md border border-white/20 rounded-lg p-2 shadow-lg">
                                                <p className="text-xs text-white/90">Amount of $LABS tokens purchased</p>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </th>
                                      <th className="text-right py-4 px-4 text-white/80 font-medium">
                                        <div className="flex items-center justify-end gap-2">
                                          % Contributed
                                          <div className="relative group">
                                            <svg className="w-4 h-4 text-white/40 hover:text-white/70 transition-colors cursor-help" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                            </svg>
                                            <div className="absolute right-0 top-6 z-20 opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity duration-200 whitespace-nowrap">
                                              <div className="bg-black/80 backdrop-blur-md border border-white/20 rounded-lg p-2 shadow-lg">
                                                <p className="text-xs text-white/90">Percentage of total fundraising contribution</p>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </th>
                                      <th className="text-right py-4 px-4 text-white/80 font-medium">
                                        <div className="flex items-center justify-end gap-2">
                                          % Revenue Allocation
                                          <div className="relative group">
                                            <svg className="w-4 h-4 text-white/40 hover:text-white/70 transition-colors cursor-help" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                            </svg>
                                            <div className="absolute right-0 top-6 z-20 opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity duration-200 whitespace-nowrap">
                                              <div className="bg-black/80 backdrop-blur-md border border-white/20 rounded-lg p-2 shadow-lg">
                                                <p className="text-xs text-white/90">Share of the 10% OPX revenue for 2 months</p>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    {sortedTopParticipants.map((entry) => (
                                      <tr 
                                        key={entry.walletAddress} 
                                        className="border-b border-white/5 hover:bg-white/5 transition-colors"
                                      >
                                        <td className="py-4 px-4">
                                          <a 
                                            href={`https://solscan.io/account/${entry.walletAddress}`}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="font-mono text-white/90 hover:text-white/70 transition-colors duration-300 inline-flex items-center gap-1"
                                          >
                                            {formatWalletAddress(entry.walletAddress)}
                                            <svg className="w-3 h-3 opacity-60" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                                            </svg>
                                          </a>
                                        </td>
                                        <td className="py-4 px-4 text-right">
                                          <div className="font-semibold text-[#4a85ff]">
                                            {formatNumber(entry.labsQuantity)}
                                          </div>
                                        </td>
                                        <td className="py-4 px-4 text-right">
                                          <div className="text-white/80">
                                            {formatPercentage(entry.percentageAllocation)}
                                          </div>
                                        </td>
                                        <td className="py-4 px-4 text-right">
                                          <div className="text-green-400 font-semibold">
                                            {formatPercentage(entry.percentageAllocation * 0.1)}
                                          </div>
                                        </td>
                                      </tr>
                                    ))}
                                  </tbody>
                                </table>
                              </div>

                              {/* Mobile Cards */}
                              <div className="md:hidden space-y-2">
                                {sortedTopParticipants.map((entry) => (
                                  <div 
                                    key={entry.walletAddress}
                                    className="bg-gradient-to-br from-white/5 to-white/[0.02] rounded-lg p-3 border border-white/10"
                                  >
                                    <div className="mb-2">
                                      <a 
                                        href={`https://solscan.io/account/${entry.walletAddress}`}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="font-mono text-white/90 hover:text-white/70 transition-colors duration-300 text-sm inline-flex items-center gap-1.5"
                                      >
                                        {formatWalletAddress(entry.walletAddress)}
                                        <svg className="w-3 h-3 opacity-60" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                                        </svg>
                                      </a>
                                    </div>
                                    <div className="grid grid-cols-3 gap-2 text-xs">
                                      <div className="text-center">
                                        <div className="text-white/50 mb-1">$LABS</div>
                                        <div className="font-semibold text-[#4a85ff] text-sm">
                                          {formatNumber(entry.labsQuantity)}
                                        </div>
                                      </div>
                                      <div className="text-center">
                                        <div className="text-white/50 mb-1">Contributed</div>
                                        <div className="text-white/80 text-sm">
                                          {formatPercentage(entry.percentageAllocation)}
                                        </div>
                                      </div>
                                      <div className="text-center">
                                        <div className="text-white/50 mb-1">Revenue</div>
                                        <div className="text-green-400 font-semibold text-sm">
                                          {formatPercentage(entry.percentageAllocation * 0.1)}
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                ))}
                              </div>

                              {participantsData.length > 100 && (
                                <div className="mt-6 text-center text-white/60 text-sm">
                                  Showing top 100 participants out of {participantsData.length} total unique buyers
                                </div>
                              )}
                            </AccordionItem>
                          </Accordion>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
}
